export const Data = {
  Physics: {
    "1st Paper": {
      "1": "Physical World & Measurement",
      "2": "Vectors",
      "3": "Dynamics",
      "4": "Newtonian Mechanics",
      "5": "Work, Energy & Power",
      "6": "Gravitation & Gravity",
      "7": "Structural Properties of Matter",
      "8": "Periodic Motion",
      "9": "Waves",
      "10": "Ideal Gas & Kinetic Theory of Gases",
    },
    "2nd Paper": {
      "1": "Thermodynamics",
      "2": "Static Electricity",
      "3": "Current Electricity",
      "4": "Magnetic Effects of Electric Current & Magnetism",
      "5": "Electromagnetic Induction & Alternating Current",
      "6": "Geometrical Optics",
      "7": "Physical Optics",
      "8": "Beginning of Modern Physics",
      "9": "Atomic Model & Nuclear Physics",
      "10": "Semiconductor & Electronics",
      "11": "Astronomy",
    },
  },
  Chemistry: {
    "1st Paper": {
      "1": "Safe Use of Laboratory",
      "2": "Qualitative Chemistry",
      "3": "Periodic Properties of Elements & Chemical Bonding",
      "4": "Chemical Changes",
      "5": "Applications of Chemistry",
    },
    "2nd Paper": {
      "1": "Environmental Chemistry",
      "2": "Organic Chemistry",
      "3": "Quantitative Chemistry",
      "4": "Electrochemistry",
      "5": "Economic Chemistry",
    },
  },
  "Higher Math": {
    "1st Paper": {
      "1": "Matrices & Determinants",
      "2": "Vectors",
      "3": "Straight Lines",
      "4": "Circles",
      "5": "Permutations & Combinations",
      "6": "Trigonometric Ratios",
      "7": "Trigonometric Ratios of Associated Angles",
      "8": "Functions & Graph of Functions",
      "9": "Differentiation",
      "10": "Integration",
    },
    "2nd Paper": {
      "1": "Real Numbers & Inequalities",
      "2": "Linear Programming",
      "3": "Complex Numbers",
      "4": "Polynomials & Polynomial Equations",
      "5": "Binomial Expansions",
      "6": "Conics",
      "7": "Inverse Trigonometric Funtions & Trigonometric Equations",
      "8": "Statics",
      "9": "Motion of Particles in a Plane",
      "10": "Measures of Dispersions & Probability",
    },
  },
  Biology: {
    "1st Paper": {
      "1": "Cell & Its Structure",
      "2": "Cell Division",
      "3": "Cell Chemistry",
      "4": "Micro Organism / Microbe",
      "5": "Algae & Fungi",
      "6": "Bryophyta & Pteridophyta",
      "7": "Gymnosperms & Angiosperms",
      "8": "Tissue & Tissue System",
      "9": "Plant Physiology",
      "10": "Plant Reproduction",
      "11": "Biotechnology",
      "12": "Environment, Distribution & Conservation of Living Organisms",
    },
    "2nd Paper": {
      "1": "Animal Diversity & Classification",
      "2": "Animal Identity",
      "3": "Human Physiology: Digestion & Absorption",
      "4": "Human Physiology: Blood & Circulation",
      "5": "Human Physiology: Respiration & Breathing",
      "6": "Human Physiology: Wastes & Elimination",
      "7": "Human Physiology: Locomotion & Movement",
      "8": "Human Physiology: Coordination & Control",
      "9": "Continuation of Human Life",
      "10": "Protection of Human Body (Immunity)",
      "11": "Genetics & Evolution",
      "12": "Animal Behavior",
    },
  },
  ICT: {
    "1": "Information & Communication Technology: World & Bangladesh Perspective",
    "2": "Communication System & Networking",
    "3": "Number Systems & Digital Devices",
    "4": "Introduction to Web Design & HTML",
    "5": "Programming Language",
    "6": "Database Management System",
  },
  Bengali: {
    "1st Paper": {
      Prose: {
        "1": "বাঙ্গালার নব্য লেখকদিগের প্রতি নিবেদন—বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
        "2": "অপরিচিতা—রবীন্দ্রনাথ ঠাকুর",
        "3": "সাহিত্যে খেলা—প্রমথ চৌধুরী",
        "4": "বিলাসী—শরৎচন্দ্র চট্টোপাধ্যায়",
        "5": "অর্ধাঙ্গী—রোকেয়া সাখাওয়াত হোসেন",
        "6": "যৌবনের গান—কাজী নজরুল ইসলাম",
        "7": "জীবন ও বৃক্ষ—মোতাহের হোসেন চৌধুরী",
        "8": "গন্তব্য কাবুল—সৈয়দ মুজতবা আলী",
        "9": "মাসি-পিসি—মানিক বন্দ্যোপাধ্যায়",
        "10": "কপিলদাস মুর্মুর শেষ কাজ—শওকত আলী",
        "11": "রেইনকোট—আখতারুজ্জামান ইলিয়াস",
        "12": "নেকলেস—গী দ্য মোপাসাঁ",
      },
      Poetry: {
        "1": "ঋতু-বর্ণন—আলাওল",
        "2": "বিভীষণের প্রতি মেঘনাদ—মাইকেল মধুসূদন দত্ত",
        "3": "সোনার তরী—রবীন্দ্রনাথ ঠাকুর",
        "4": "বিদ্রোহী—কাজী নজরুল ইসলাম",
        "5": "সুচেতনা—জীবনানন্দ দাশ",
        "6": "প্রতিদান—জসীমউদ্দীন",
        "7": "তাহারেই পড়ে মনে—সুফিয়া কামাল",
        "8": "পদ্মা—ফরুখ আহমদ",
        "9": "ফেব্রুয়ারি ১৯৬৯—শামসুর রাহমান",
        "10": "আঠার বছর বয়স—সুকান্ত ভট্টাচার্য",
        "11": "আমি কিংবদন্তির কথা বলছি—আবু জাফর ওবায়দুল্লাহ্",
        "12": "প্রত্যাবর্তনের লজ্জা—আল মাহমুদ",
      },
    },
    "2nd Paper": {},
  },
} as const;

export type Subject = keyof typeof Data;
export type Paper = "1st Paper" | "2nd Paper";
